marineproject/marineapp/urls.py
from django.urls import path, include, re_path
from .views import *
from django_email_verification import urls as email_urls
from . import views
# from verify_email import urls as mail_urls  #MIGHT HAVE ERROR

app_name = "marineapp"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("", LogInView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("maindashboard/", MainDashboardView.as_view(), name="maindashboard"),
    # path('verification/', VerificationView.as_view(), name='verify_email'),
    re_path('^send_email/$', sendEmail),
    path('email/', include(email_urls)),
    path("maindashboard/hrdashboard/",
         HRDashboardView.as_view(),
         name="hrdashboard"),
    path("maindashboard/traineedashboard/",
         TraineeDashboardView.as_view(),
         name="traineedashboard"),
    path("maindashboard/trainerdashboard/",
         TrainerDashboardView.as_view(),
         name="trainerdashboard"),
    path("maindashboard/virtual-tour/",
         VirtualTourView.as_view(),
         name="virtualtour"),
    path("match-learn-instructions/",
         MatchInstructionView.as_view(),
         name="matchinstruction"),
    path("module1-lesson/", Module1LessonView.as_view(), name="module1lesson"),
    path("match-game/", MatchGameView.as_view(), name="matchgame"),
    path("module2-lesson/", Module2LessonView.as_view(), name="module2lesson"),
    path("module3-lesson/", Module3LessonView.as_view(), name="module3lesson"),
    path("module4-lesson/", Module4LessonView.as_view(), name="module4lesson"),
    path("module5-lesson/", Module5LessonView.as_view(), name="module5lesson"),
    path("hangman-instruction/",
         HangmanInstructionView.as_view(),
         name="hangmaninstruction"),
    path("match-game/", MatchGameView.as_view(), name="matchgame"),
    path("hangman-game/", HangmanGameView.as_view(), name="hangmangame"),
    path("lessonmaterial-module1/",
         LessonMaterialModule1View.as_view(),
         name="lessonmaterialmodule1"),
    path("lessonmaterial-module1/",
         LessonMaterialModule1View.as_view(),
         name="lessonmaterialmodule1"),
    path("lessonmaterial-module2/",
         LessonMaterialModule2View.as_view(),
         name="lessonmaterialmodule2"),
    path("lessonmaterial-module3/",
         LessonMaterialModule3View.as_view(),
         name="lessonmaterialmodule3"),
    path("lessonmaterial-module4/",
         LessonMaterialModule4View.as_view(),
         name="lessonmaterialmodule4"),
    path("lessonmaterial-module5/",
         LessonMaterialModule5View.as_view(),
         name="lessonmaterialmodule5"),
    path("engine-room/", EngineRoomView.as_view(), name="engineroom"),
    path("delete_topic/(?P<module>[0-9]+)$/(?P<topic>[0-9]+)$",
         DeleteRowView.as_view(),
         name="deleterow"),
]

marineproject/marineproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("marineapp.urls")),
    path('verification/', include('verify_email.urls')),  #Email Verification
    path('quiz/', include('quizes.urls', namespace='quizes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marineproject/quizes/urls.py
from django.urls import path

from .views import *
from django.urls import path
from .views import (QuizListView, quiz_view, quiz_data_view, save_quiz_view)

from .views import (QuizListView, quiz_view, quiz_data_view, save_quiz_view)

app_name = 'quizes'

urlpatterns = [
    # path('', QuizListView.as_view(), name='quiz1'),
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

marineproject/quizes/models.py
from django.db import models
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)


class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(
        help_text="required score in %")
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        # return self.question_set.all()[:self.number_of_questions]
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quiz 1'


# class Quiz4(models.Model):
#     name = models.CharField(max_length=120)
#     topic = models.CharField(max_length=120)
#     number_of_questions = models.IntegerField()
#     time = models.IntegerField(help_text="duration of the quiz in minutes")
#     required_score_to_pass = models.IntegerField(
#         help_text="required score in %")
#     difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

#     def __str__(self):
#         return f"{self.name}-{self.topic}"

#     def get_questions(self):
#         # return self.question_set.all()[:self.number_of_questions]
#         questions = list(self.question_set.all())
#         random.shuffle(questions)
#         return questions[:self.number_of_questions]

#     class Meta:
#         verbose_name_plural = 'Quiz 4'

marineproject/quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result


class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({
                    str(q): {
                        'correct_answer': correct_answer,
                        'answered': a_selected
                    }
                })
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({
                'passed': True,
                'score': score_,
                'results': results
            })
        else:
            return JsonResponse({
                'passed': False,
                'score': score_,
                'results': results
            })

marineproject/templates/quizes/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'style.css' %}>

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
</head>

<body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</body>

</html>

marineproject/templates/quizes/main.html
{% extends "quizes/base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'js/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-confirm"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
                <button type="button" id="start-button" class="btn btn-success">yes</button>
            </div>
        </div>
    </div>
</div>

<div class="h1">Quiz List</div>
<hr>
{% for obj in object_list %}
<button class="btn btn-link modal-button" data-pk="{{obj.pk}}" data-quiz="{{obj.name}}"
    data-questions="{{obj.number_of_questions}}" data-difficulty="{{obj.difficluty}}" data-time="{{obj.time}}"
    data-pass="{{obj.required_score_to_pass}}" data-toggle="modal" data-target="#quizStartModal">
    {{obj.name}}
</button><br>

{% endfor %}
{% endblock content %}

marineproject/templates/quizes/quiz.html
{% extends "quizes/base.html" %}
{% load static %}


{% block scripts %}
<script src="{% static 'js/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
<a href="{% url 'marineapp:traineedashboard' %}" class="btn btn-primary mt-3">Trainee Dashboard</a>
{% endblock content %}